-- Storage bucket for generated invoice PDFs (generate-invoice-pdf Edge
-- Function). Private, not public — these files contain customer name,
-- WhatsApp number, address, and purchase details (PII). Every read goes
-- through a short-lived signed URL (see _shared/invoicePdf.ts's
-- getInvoiceSignedUrl), generated by the service-role Edge Function itself,
-- so no anon/public read policy is needed here — same reasoning as
-- add_qr_codes_bucket.sql being public for the opposite reason (no PII).

INSERT INTO storage.buckets (id, name, public)
VALUES ('invoices', 'invoices', false)
ON CONFLICT (id) DO NOTHING;

-- Verify:
-- SELECT id, name, public FROM storage.buckets WHERE id = 'invoices';
